const express=require("express");const{asyncRoute,AppError}=require("../utils/errors");const{requireFields,numeric}=require("../validators/common");
function costsRoutes({costs,costEngine,audit}){const r=express.Router();const logged=async(req,action,type,id,before,after)=>audit.record({actor:req.user.username,action,entityType:type,entityId:String(id||after?.id||""),before,after,ip:req.ip,requestId:req.id});
  r.get("/cost-items",asyncRoute(async(req,res)=>res.json({status:"ok",items:await costs.listCostItems()})));
  r.post("/cost-items",asyncRoute(async(req,res)=>{numeric(requireFields(req.body,["item_code","item_name","unit_cost"]),["unit_cost","unit_desi"]);const data=await costs.saveCostItem(req.body);await logged(req,"COST_ITEM_CREATED","cost_item",data.id,null,data);res.status(201).json({status:"ok",data});}));
  r.patch("/cost-items/:id",asyncRoute(async(req,res)=>{numeric(requireFields(req.body,["item_code","item_name","unit_cost"]),["unit_cost","unit_desi"]);const data=await costs.saveCostItem(req.body,req.params.id);if(!data)throw new AppError("Maliyet kalemi bulunamadı",404);await logged(req,"COST_ITEM_UPDATED","cost_item",data.id,null,data);res.json({status:"ok",data});}));
  r.delete("/cost-items/:id",asyncRoute(async(req,res)=>{const data=await costs.deleteCostItem(req.params.id);if(!data)throw new AppError("Maliyet kalemi bulunamadı",404);await logged(req,"COST_ITEM_DELETED","cost_item",data.id,data,null);res.json({status:"ok"});}));
  r.get("/mappings",asyncRoute(async(req,res)=>res.json({status:"ok",items:await costs.listMappings(req.query)})));
  r.post("/mappings/validate",asyncRoute(async(req,res)=>res.json({status:"ok",data:await costs.validateMappings(req.body.rows)})));
  r.post("/mappings/bulk",asyncRoute(async(req,res)=>{const data=await costs.replaceMappings(req.body.rows);await costEngine.recalculate();await logged(req,"MAPPINGS_ATOMIC_REPLACE","mapping","TRENDYOL",null,data);res.json({status:"ok",data});}));
  r.post("/mappings",asyncRoute(async(req,res)=>{const data=await costs.upsertMapping(req.body);await costEngine.recalculate(req.body.barcode);await logged(req,"MAPPING_UPSERTED","mapping",data.id,null,data);res.status(201).json({status:"ok",data});}));
  r.patch("/mappings/:id",asyncRoute(async(req,res)=>{const data=await costs.updateMapping(req.params.id,req.body);if(!data)throw new AppError("Mapping bulunamadı",404);await costEngine.recalculate(req.body.barcode);await logged(req,"MAPPING_UPDATED","mapping",data.id,null,data);res.json({status:"ok",data});}));
  r.delete("/mappings/:id",asyncRoute(async(req,res)=>{const data=await costs.deleteMapping(req.params.id);if(!data)throw new AppError("Mapping bulunamadı",404);await costEngine.recalculate(data.barcode);await logged(req,"MAPPING_DELETED","mapping",data.id,data,null);res.json({status:"ok"});}));
  r.get("/commissions",asyncRoute(async(req,res)=>res.json({status:"ok",items:await costs.listCommissions()})));
  r.post("/commissions",asyncRoute(async(req,res)=>{numeric(requireFields(req.body,["category_id","commission_rate"]),["commission_rate"]);const data=await costs.saveCommission(req.body);await costEngine.recalculate();await logged(req,"COMMISSION_SAVED","commission",data.category_id,null,data);res.json({status:"ok",data});}));
  r.patch("/commissions/:categoryId",asyncRoute(async(req,res)=>{const data=await costs.saveCommission({...req.body,category_id:req.params.categoryId});await costEngine.recalculate();await logged(req,"COMMISSION_UPDATED","commission",data.category_id,null,data);res.json({status:"ok",data});}));
  r.get("/shipping",asyncRoute(async(req,res)=>res.json({status:"ok",data:await costs.shipping()})));
  r.get("/shipping/rates",asyncRoute(async(req,res)=>res.json({status:"ok",items:(await costs.shipping()).rates})));
  r.get("/shipping/barems",asyncRoute(async(req,res)=>res.json({status:"ok",items:(await costs.shipping()).barems})));
  r.get("/packaging-rules",asyncRoute(async(req,res)=>res.json({status:"ok",items:(await costs.shipping()).packaging})));
  r.post("/shipping/rates",asyncRoute(async(req,res)=>{const data=await costs.saveShippingRate(req.body);await logged(req,"SHIPPING_RATE_SAVED","shipping_rate",data.id,null,data);res.json({status:"ok",data});}));
  r.post("/shipping/barems",asyncRoute(async(req,res)=>{const data=await costs.saveBarem(req.body);await logged(req,"SHIPPING_BAREM_SAVED","shipping_barem",data.id,null,data);res.json({status:"ok",data});}));
  r.post("/packaging-rules",asyncRoute(async(req,res)=>{const data=await costs.savePackaging(req.body);await logged(req,"PACKAGING_RULE_SAVED","packaging_rule",data.id,null,data);res.json({status:"ok",data});}));
  r.patch("/packaging-rules/:id",asyncRoute(async(req,res)=>{const data=await costs.savePackaging(req.body,req.params.id);await logged(req,"PACKAGING_RULE_UPDATED","packaging_rule",data.id,null,data);res.json({status:"ok",data});}));
  r.delete("/packaging-rules/:id",asyncRoute(async(req,res)=>{const data=await costs.deletePackaging(req.params.id);await logged(req,"PACKAGING_RULE_DELETED","packaging_rule",data.id,data,null);res.json({status:"ok"});}));
  return r;}
module.exports={costsRoutes};
