const express=require("express");const{asyncRoute,AppError}=require("../utils/errors");const{pagination}=require("../validators/common");
function productsRoutes({products,costEngine,audit,repricer}){const r=express.Router();
  r.get("/",asyncRoute(async(req,res)=>{const page=pagination(req.query);const filters={...req.query,...page,active:req.query.active==null?undefined:req.query.active==="true",stocked:req.query.stocked==null?undefined:req.query.stocked==="true",autoUpdate:req.query.autoUpdate==null?undefined:req.query.autoUpdate==="true"};res.json({status:"ok",...(await products.list(filters))});}));
  r.get("/:barcode",asyncRoute(async(req,res)=>{const item=await products.get(req.params.barcode);if(!item)throw new AppError("Ürün bulunamadı",404,"PRODUCT_NOT_FOUND");res.json({status:"ok",data:item});}));
  r.patch("/:barcode",asyncRoute(async(req,res)=>{const before=await products.get(req.params.barcode);if(!before)throw new AppError("Ürün bulunamadı",404,"PRODUCT_NOT_FOUND");const data=await products.updateSettings(req.params.barcode,req.body);await audit.record({actor:req.user.username,action:"PRODUCT_SETTINGS_UPDATED",entityType:"product",entityId:req.params.barcode,before:before.settings,after:data,ip:req.ip,requestId:req.id});res.json({status:"ok",data});}));
  r.get("/:barcode/cost-breakdown",asyncRoute(async(req,res)=>{const data=await products.breakdown(req.params.barcode);if(!data)throw new AppError("Ürün bulunamadı",404,"PRODUCT_NOT_FOUND");res.json({status:"ok",data});}));
  for(const[type,path]of[["buybox","buybox-history"],["price","price-history"],["repricer","repricer-history"]])r.get(`/:barcode/${path}`,asyncRoute(async(req,res)=>res.json({status:"ok",items:await products.history(req.params.barcode,type)})));
  r.post("/:barcode/recalculate",asyncRoute(async(req,res)=>res.json({status:"ok",data:await costEngine.recalculate(req.params.barcode)})));
  r.post("/:barcode/manual-price-action",asyncRoute(async(req,res)=>{const price=Number(req.body.price);if(!Number.isFinite(price)||price<=0)throw new AppError("Geçerli fiyat zorunlu",400,"INVALID_PRICE");const data=await repricer.manualAction(req.params.barcode,price,req.user.username);res.status(201).json({status:"ok",data});}));
  return r;}
module.exports={productsRoutes};
